### ISSUE TITLE
[Unexpected error] : Could not load extent layer 

### ISSUE THREAD

**Issue by SimonTarabon** [MathieuChailloux/MitiConnect#10]
Workspace : /Users/simontarabon/Graphab/ERC-TVB/TOULOUSE/Tests/t01
Extent layer : /Users/simontarabon/Graphab/ERC-TVB/TOULOUSE/DATA_OS_2022/Emprises/PERIMETRE_TOULOUSE_METRO_3KM.shp

Import data : [2022-09-21 11:46:31] [Unexpected error] : Could not load layer '/Users/simontarabon/Graphab/ERC-TVB/TOULOUSE/Tests/DATA_OS_2022/Emprises/PERIMETRE_TOULOUSE_METRO_3KM.shp'

>>>> /Tests/ en trop dans le chemin de l'erreur, ça vient de moi ?

**Comment by MathieuChailloux** [comment]
Fixed by 63b6e43
