### ISSUE TITLE
Interface onglet 6 - Launches

### ISSUE THREAD

**Issue by SimonTarabon** [MathieuChailloux/MitiConnect#21]
À quoi sert tout l'espace et/ou la table dans cet onglet ?

<img width="1061" alt="Capture d’écran 2022-10-14 à 17 15 22" src="https://user-images.githubusercontent.com/113454252/195881885-9a6325c8-a28a-41f4-a8cd-829c725d286e.png">

Comme on choisit les espèces et les scénarios via les listes en dessous, peut-être qu'on pourra optimiser un max le visuel de cet onglet ? Je ne connais pas les limites de dév mais je me dis que l'attractivité de l'outil tiendra principalement de cette partie. J'avais ça en tête par exemple :

![Visuel_ 6-Launches](https://user-images.githubusercontent.com/113454252/195889960-6d85472e-709e-4b02-a2d9-a93f487f8e5d.jpg)

Cela me permet de te faire à la même occasion des petites suggestions sur le nom des boutons ou autres pour que ce soit le plus explicite / visuel / ludique possible (pour avis bien entendu). Aussi :
- est-ce que ce serait pas pertinent d'un seul bouton lancer projet(s) et jeu(x) de liens ?
- pour le graphe de comparaison des scénarios, on en reparlera mais ce serait bien d'avoir un taux de variation de EC ou PC sur la base de l'état initial ?

**Comment by MathieuChailloux** [comment]
Table conservée pour les métriques / capacité de dispersion.
