### ISSUE TITLE
Sélection valeur fixe de rasterisation lors de l'import de couches vecteurs

### ISSUE THREAD

**Issue by SimonTarabon** [MathieuChailloux/MitiConnect#44]
Impossible de renseigner une valeur en sélectionnant Valeur fixe. Zone grisée

<img width="420" alt="Capture d’écran 2023-08-23 à 11 40 51" src="https://github.com/MathieuChailloux/MitiConnect/assets/113454252/9016def0-8921-46f2-9b45-1e7202eb6b14">

**Comment by MathieuChailloux** [comment]
Fixed by classModel devs
